[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "swmm-bmi"
description = "BMI wrapper for EPA SWMM5, compatible with eWaterCycle."
license = "Apache-2.0"
version = "0.1.0"
authors = [
  { name = "Mark Melotto" },
]

dependencies = [
  "bmipy",
  "numpy",
  "pyswmm",
  "pyyaml",
]
